In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv('dataset.csv')
movies

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                 genre original_language  \
0                                          Drama,Crime                en   
1                                 Comedy,Drama,Romance                hi   
2                                          Drama,Crime                en   
3                                    Drama,History,War                en   
4                                          Drama,Crime                en   
...                                                ...               ...   
9995                          Action,Adventure,Fantasy                en   
9996  Action,TV Movie,Science Fiction,Comedy,Adventure                en   
9997                        Action,Science Fiction,War                en   
9998                    Adventure,Fantasy,Action,Drama                en   
9999                             Thriller,Action,Crime                en   

                                               overview  popularity  \
0     Framed in the 1940s for the double murder of h...      94.075   
1     Raj is a rich, carefree, happy-go-lucky second...      25.408   
2     Spanning the years 1945 to 1955, a chronicle o...      90.585   
3     The true story of how businessman Oskar Schind...      44.761   
4     In the continuing saga of the Corleone crime f...      57.749   
...                                                 ...         ...   
9995  The story follows the adventures of Aang, a yo...      98.322   
9996  The sharks take bite out of the East Coast whe...      12.490   
9997  During World War II, a brave, patriotic Americ...      18.333   
9998  A man named Farmer sets out to rescue his kidn...      15.159   
9999  Seeking justice for his partner’s murder by an...      16.482   

     release_date  vote_average  vote_count  
0      1994-09-23           8.7       21862  
1      1995-10-19           8.7        3731  
2      1972-03-14           8.7       16280  
3      1993-12-15           8.6       12959  
4      1974-12-20           8.6        9811  
...           ...           ...         ...  
9995   2010-06-30           4.7        3347  
9996   2015-07-22           4.7         417  
9997   1990-12-14           4.6         332  
9998   2007-11-29           4.7         668  
9999   2019-05-31           4.6         221  

[10000 rows x 9 columns]

In [3]:
movies.describe()

id    popularity  vote_average    vote_count
count   10000.000000  10000.000000  10000.000000  10000.000000
mean   161243.505000     34.697267      6.621150   1547.309400
std    211422.046043    211.684175      0.766231   2648.295789
min         5.000000      0.600000      4.600000    200.000000
25%     10127.750000      9.154750      6.100000    315.000000
50%     30002.500000     13.637500      6.600000    583.500000
75%    310133.500000     25.651250      7.200000   1460.000000
max    934761.000000  10436.917000      8.700000  31917.000000

In [4]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 10000 non-null  int64  
 1   title              10000 non-null  object 
 2   genre              9997 non-null   object 
 3   original_language  10000 non-null  object 
 4   overview           9987 non-null   object 
 5   popularity         10000 non-null  float64
 6   release_date       10000 non-null  object 
 7   vote_average       10000 non-null  float64
 8   vote_count         10000 non-null  int64  
dtypes: float64(2), int64(2), object(5)
memory usage: 703.3+ KB


In [5]:
movies.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

Feature Selection Part

In [6]:
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [7]:
movies1 = movies[['id', 'title', 'genre', 'overview']]
movies1

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                 genre  \
0                                          Drama,Crime   
1                                 Comedy,Drama,Romance   
2                                          Drama,Crime   
3                                    Drama,History,War   
4                                          Drama,Crime   
...                                                ...   
9995                          Action,Adventure,Fantasy   
9996  Action,TV Movie,Science Fiction,Comedy,Adventure   
9997                        Action,Science Fiction,War   
9998                    Adventure,Fantasy,Action,Drama   
9999                             Thriller,Action,Crime   

                                               overview  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[10000 rows x 4 columns]

In [8]:
movies1['tag']=movies1['overview']+movies1['genre']

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_21092\4291272766.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies1['tag']=movies1['overview']+movies1['genre']


In [9]:
new_data = movies1.drop(columns=['overview','genre'])

In [10]:
new_data

id                                          title  \
0        278                       The Shawshank Redemption   
1      19404                    Dilwale Dulhania Le Jayenge   
2        238                                  The Godfather   
3        424                               Schindler's List   
4        240                         The Godfather: Part II   
...      ...                                            ...   
9995   10196                             The Last Airbender   
9996  331446                       Sharknado 3: Oh Hell No!   
9997   13995                                Captain America   
9998    2312  In the Name of the King: A Dungeon Siege Tale   
9999  455957                                         Domino   

                                                    tag  
0     Framed in the 1940s for the double murder of h...  
1     Raj is a rich, carefree, happy-go-lucky second...  
2     Spanning the years 1945 to 1955, a chronicle o...  
3     The true story of how businessman Oskar Schind...  
4     In the continuing saga of the Corleone crime f...  
...                                                 ...  
9995  The story follows the adventures of Aang, a yo...  
9996  The sharks take bite out of the East Coast whe...  
9997  During World War II, a brave, patriotic Americ...  
9998  A man named Farmer sets out to rescue his kidn...  
9999  Seeking justice for his partner’s murder by an...  

[10000 rows x 3 columns]

1. Bag of word
2. TFIDF


In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:

cv=CountVectorizer(max_features=10000, stop_words='english')

In [13]:
cv

CountVectorizer(max_features=10000, stop_words='english')

In [14]:
vector = cv.fit_transform(movies['overview'].values.astype('U')).toarray()

In [15]:
vector.shape

(10000, 10000)

In [16]:
from sklearn.metrics.pairwise import cosine_similarity
similarrity = cosine_similarity(vector)
similarrity

array([[1.        , 0.03030303, 0.02861819, ..., 0.0836242 , 0.08444007,
        0.03481553],
       [0.03030303, 1.        , 0.05723638, ..., 0.        , 0.        ,
        0.        ],
       [0.02861819, 0.05723638, 1.        , ..., 0.02632491, 0.03987261,
        0.        ],
       ...,
       [0.0836242 , 0.        , 0.02632491, ..., 1.        , 0.        ,
        0.        ],
       [0.08444007, 0.        , 0.03987261, ..., 0.        , 1.        ,
        0.        ],
       [0.03481553, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [17]:
new_data[new_data['title']=='Once Upon a Time in America'].index[0]

26

In [18]:
distance = sorted(list(enumerate(similarrity[2])),reverse=True,key=lambda vector:vector[1])
for i in distance[0:5]:
  print(movies.iloc[i[0]].title)

The Godfather
The Godfather: Part II
Kind Hearts and Coronets
Sinister
Still Walking


In [23]:
def recomand(movie):
  index = movies[movies['title']==movie].index[0]
  distance = sorted(list(enumerate(similarrity[index])),reverse=True,key=lambda vector:vector[1])
  for i in distance[0:5]:
    print(movies.iloc[i[0]].title)

In [24]:
recomand('Iron Man')

Iron Man
Clown
Iron Man 2
The Wizards Return: Alex vs. Alex
G.O.R.A.


In [27]:
top15_popular = movies.sort_values(by='popularity',ascending=False).head(15)
top15_popular = top15_popular[['id','title']]
top15_popular

id                                        title
3066  507086                      Jurassic World Dominion
1337  438148                     Minions: The Rise of Gru
4522  616037                       Thor: Love and Thunder
61    361743                            Top Gun: Maverick
388   756999                              The Black Phone
1990  718789                                    Lightyear
1313  453395  Doctor Strange in the Multiverse of Madness
2815  759175                                 The Princess
3103  836225                          The Exorcism of God
948   560057                                The Sea Beast
258   634649                      Spider-Man: No Way Home
837   675353                         Sonic the Hedgehog 2
1574  626735                                          Dog
556   810693                             Jujutsu Kaisen 0
4025  338953  Fantastic Beasts: The Secrets of Dumbledore

In [21]:
import pickle
pickle.dump(movies, open('movie_list.pkl','wb'))
pickle.dump(similarrity,open('similarrity.pkl','wb'))
pickle.load(open('movie_list.pkl','rb'))
pickle.load(open('similarrity.pkl','rb'))

array([[1.        , 0.03030303, 0.02861819, ..., 0.0836242 , 0.08444007,
        0.03481553],
       [0.03030303, 1.        , 0.05723638, ..., 0.        , 0.        ,
        0.        ],
       [0.02861819, 0.05723638, 1.        , ..., 0.02632491, 0.03987261,
        0.        ],
       ...,
       [0.0836242 , 0.        , 0.02632491, ..., 1.        , 0.        ,
        0.        ],
       [0.08444007, 0.        , 0.03987261, ..., 0.        , 1.        ,
        0.        ],
       [0.03481553, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [28]:
import pickle
pickle.dump(top15_popular,open('top15_popular.pkl','wb'))
pickle.load(open('top15_popular.pkl','rb'))

id                                        title
3066  507086                      Jurassic World Dominion
1337  438148                     Minions: The Rise of Gru
4522  616037                       Thor: Love and Thunder
61    361743                            Top Gun: Maverick
388   756999                              The Black Phone
1990  718789                                    Lightyear
1313  453395  Doctor Strange in the Multiverse of Madness
2815  759175                                 The Princess
3103  836225                          The Exorcism of God
948   560057                                The Sea Beast
258   634649                      Spider-Man: No Way Home
837   675353                         Sonic the Hedgehog 2
1574  626735                                          Dog
556   810693                             Jujutsu Kaisen 0
4025  338953  Fantastic Beasts: The Secrets of Dumbledore

In [22]:
import numpy as np
np.save("similarity", similarrity)
np.load("similarity.npy")

array([[1.        , 0.03030303, 0.02861819, ..., 0.0836242 , 0.08444007,
        0.03481553],
       [0.03030303, 1.        , 0.05723638, ..., 0.        , 0.        ,
        0.        ],
       [0.02861819, 0.05723638, 1.        , ..., 0.02632491, 0.03987261,
        0.        ],
       ...,
       [0.0836242 , 0.        , 0.02632491, ..., 1.        , 0.        ,
        0.        ],
       [0.08444007, 0.        , 0.03987261, ..., 0.        , 1.        ,
        0.        ],
       [0.03481553, 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])